#!/usr/bin/python2

import traceback, sys, os, re, psycopg2, psycopg2.extras
from util import *

class BadSubmit(Exception): pass

try:
    conn=psycopg2.connect('dbname=factory')
    cur=conn.cursor()

    cur.execute("select column_name from information_schema.columns where table_name='provisioned' and column_name like 'p_%' order by column_name")
    columns=["deviceid","date_trunc('seconds',updated)"]+[x[0] for x in cur.fetchall()]
    titles=["Device ID","Updated"]+[x.replace("p_","").title() for x in columns[2:]]

    cur.execute("select %s from provisioned order by updated desc" % ','.join(columns))
    rows=cur.fetchall()

    content=table(("list",[titles]+[list(r) for r in rows]))

    # print generated content
    print html("Provisioned Data", content + tick_footer())

except:
    print "Content-type: text/plain\n\nAn error has occurred"
    print
    traceback.print_exc(file = sys.stdout)
    #print
    #for k in sorted(form.keys()): print k,"=",form.getvalue(k)
